-- MySQL Script generated by MySQL Workbench
-- Sun Dec  8 14:58:46 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema etudeclinique
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema etudeclinique
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `etudeclinique` DEFAULT CHARACTER SET utf8 ;
USE `etudeclinique` ;

-- -----------------------------------------------------
-- Table `etudeclinique`.`Auth`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etudeclinique`.`Auth` ;

CREATE TABLE IF NOT EXISTS `etudeclinique`.`Auth` (
  `idAuth` INT NOT NULL AUTO_INCREMENT,
  `Utilisateur_idUtilisateur` INT NOT NULL,
  `hashedPassword` VARCHAR(45) NOT NULL,
  `sel` VARCHAR(45) NOT NULL,
  `dateDerniereModification` TIMESTAMP NOT NULL,
  PRIMARY KEY (`idAuth`),
  INDEX `fk_Auth_Utilisateur1_idx` (`Utilisateur_idUtilisateur` ASC),
  CONSTRAINT `fk_Auth_Utilisateur1`
    FOREIGN KEY (`Utilisateur_idUtilisateur`)
    REFERENCES `etudeclinique`.`Utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etudeclinique`.`Chirurgie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etudeclinique`.`Chirurgie` ;

CREATE TABLE IF NOT EXISTS `etudeclinique`.`Chirurgie` (
  `idChirurgie` INT NOT NULL AUTO_INCREMENT,
  `Visite_idVisite` INT NOT NULL,
  `Utilisateur_idUtilisateur` INT NOT NULL,
  `dateChirurgie` DATETIME NOT NULL,
  PRIMARY KEY (`idChirurgie`),
  INDEX `fk_Chirurgie_Visite1_idx` (`Visite_idVisite` ASC),
  INDEX `fk_Chirurgie_Utilisateur1_idx` (`Utilisateur_idUtilisateur` ASC),
  CONSTRAINT `fk_Chirurgie_Visite1`
    FOREIGN KEY (`Visite_idVisite`)
    REFERENCES `etudeclinique`.`Visite` (`idVisite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Chirurgie_Utilisateur1`
    FOREIGN KEY (`Utilisateur_idUtilisateur`)
    REFERENCES `etudeclinique`.`Utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etudeclinique`.`Complication`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etudeclinique`.`Complication` ;

CREATE TABLE IF NOT EXISTS `etudeclinique`.`Complication` (
  `idComplication` INT NOT NULL AUTO_INCREMENT,
  `Visite_idVisite` INT NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`idComplication`, `Visite_idVisite`),
  INDEX `fk_Complication_Visite1_idx` (`Visite_idVisite` ASC),
  CONSTRAINT `fk_Complication_Visite1`
    FOREIGN KEY (`Visite_idVisite`)
    REFERENCES `etudeclinique`.`Visite` (`idVisite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etudeclinique`.`EtudeClinique`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etudeclinique`.`EtudeClinique` ;

CREATE TABLE IF NOT EXISTS `etudeclinique`.`EtudeClinique` (
  `idEtudeClinique` INT NOT NULL,
  `nomEtude` VARCHAR(150) NOT NULL,
  `description` TEXT NOT NULL,
  `dateDebut` DATETIME NOT NULL,
  `dateFin` DATETIME NOT NULL,
  PRIMARY KEY (`idEtudeClinique`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etudeclinique`.`Implant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etudeclinique`.`Implant` ;

CREATE TABLE IF NOT EXISTS `etudeclinique`.`Implant` (
  `idImplant` INT NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(45) NOT NULL,
  `fabricant` VARCHAR(45) NOT NULL,
  `modele` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idImplant`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etudeclinique`.`Log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etudeclinique`.`Log` ;

CREATE TABLE IF NOT EXISTS `etudeclinique`.`Log` (
  `idLog` INT NOT NULL AUTO_INCREMENT,
  `Utilisateur_idUtilisateur` INT NOT NULL,
  `dateAction` TIMESTAMP NOT NULL,
  `action` VARCHAR(100) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`idLog`),
  INDEX `fk_Log_Utilisateur1_idx` (`Utilisateur_idUtilisateur` ASC),
  CONSTRAINT `fk_Log_Utilisateur1`
    FOREIGN KEY (`Utilisateur_idUtilisateur`)
    REFERENCES `etudeclinique`.`Utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etudeclinique`.`Mesure`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etudeclinique`.`Mesure` ;

CREATE TABLE IF NOT EXISTS `etudeclinique`.`Mesure` (
  `idMesure` INT NOT NULL AUTO_INCREMENT,
  `Visite_idVisite` INT NOT NULL,
  `TypeMesure_idTypeMesure` INT NOT NULL,
  `valeur` DECIMAL NOT NULL,
  `unite` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMesure`),
  INDEX `fk_Mesure_Visite1_idx` (`Visite_idVisite` ASC),
  INDEX `fk_Mesure_TypeMesure1_idx` (`TypeMesure_idTypeMesure` ASC),
  CONSTRAINT `fk_Mesure_Visite1`
    FOREIGN KEY (`Visite_idVisite`)
    REFERENCES `etudeclinique`.`Visite` (`idVisite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mesure_TypeMesure1`
    FOREIGN KEY (`TypeMesure_idTypeMesure`)
    REFERENCES `etudeclinique`.`TypeMesure` (`idTypeMesure`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etudeclinique`.`Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etudeclinique`.`Role` ;

CREATE TABLE IF NOT EXISTS `etudeclinique`.`Role` (
  `idRole` INT NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idRole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etudeclinique`.`Token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etudeclinique`.`Token` ;

CREATE TABLE IF NOT EXISTS `etudeclinique`.`Token` (
  `idToken` INT NOT NULL AUTO_INCREMENT,
  `Utilisateur_idUtilisateur` INT NOT NULL,
  `token` VARCHAR(100) NOT NULL,
  `dateExpiration` TIMESTAMP NOT NULL,
  PRIMARY KEY (`idToken`),
  INDEX `fk_Token_Utilisateur1_idx` (`Utilisateur_idUtilisateur` ASC),
  CONSTRAINT `fk_Token_Utilisateur1`
    FOREIGN KEY (`Utilisateur_idUtilisateur`)
    REFERENCES `etudeclinique`.`Utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etudeclinique`.`TypeMesure`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etudeclinique`.`TypeMesure` ;

CREATE TABLE IF NOT EXISTS `etudeclinique`.`TypeMesure` (
  `idTypeMesure` INT NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idTypeMesure`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etudeclinique`.`TypeVisite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etudeclinique`.`TypeVisite` ;

CREATE TABLE IF NOT EXISTS `etudeclinique`.`TypeVisite` (
  `idTypeVisite` INT NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idTypeVisite`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etudeclinique`.`Utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etudeclinique`.`Utilisateur` ;

CREATE TABLE IF NOT EXISTS `etudeclinique`.`Utilisateur` (
  `idUtilisateur` INT NOT NULL AUTO_INCREMENT,
  `Role_idRole` INT NOT NULL,
  `nom` VARCHAR(120) NOT NULL,
  `prenom` VARCHAR(120) NOT NULL,
  `email` VARCHAR(120) NOT NULL,
  `dateCreation` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `derniereConnexion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idUtilisateur`, `Role_idRole`),
  INDEX `fk_Utilisateur_Role1_idx` (`Role_idRole` ASC),
  CONSTRAINT `fk_Utilisateur_Role1`
    FOREIGN KEY (`Role_idRole`)
    REFERENCES `etudeclinique`.`Role` (`idRole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etudeclinique`.`Visite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etudeclinique`.`Visite` ;

CREATE TABLE IF NOT EXISTS `etudeclinique`.`Visite` (
  `idVisite` INT NOT NULL AUTO_INCREMENT,
  `dateVisite` DATETIME NOT NULL,
  `TypeVisite_idTypeVisite` INT NOT NULL,
  `Utilisateur_idUtilisateur` INT NOT NULL,
  `EtudeClinique_idEtudeClinique` INT NOT NULL,
  `Implant_idImplant` INT NOT NULL,
  PRIMARY KEY (`idVisite`),
  INDEX `fk_Visite_TypeVisite1_idx` (`TypeVisite_idTypeVisite` ASC),
  INDEX `fk_Visite_Utilisateur1_idx` (`Utilisateur_idUtilisateur` ASC),
  INDEX `fk_Visite_EtudeClinique1_idx` (`EtudeClinique_idEtudeClinique` ASC),
  INDEX `fk_Visite_Implant1_idx` (`Implant_idImplant` ASC),
  CONSTRAINT `fk_Visite_TypeVisite1`
    FOREIGN KEY (`TypeVisite_idTypeVisite`)
    REFERENCES `etudeclinique`.`TypeVisite` (`idTypeVisite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visite_Utilisateur1`
    FOREIGN KEY (`Utilisateur_idUtilisateur`)
    REFERENCES `etudeclinique`.`Utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visite_EtudeClinique1`
    FOREIGN KEY (`EtudeClinique_idEtudeClinique`)
    REFERENCES `etudeclinique`.`EtudeClinique` (`idEtudeClinique`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visite_Implant1`
    FOREIGN KEY (`Implant_idImplant`)
    REFERENCES `etudeclinique`.`Implant` (`idImplant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
